name: Build, Patch and Release
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "ver/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches --no-daemon --stacktrace
      - name: Build Reobf Jar (Default)
        run: ./gradlew createReobfPaperclipJar --no-daemon --stacktrace
      - name: Generate Development Bundle
        run: ./gradlew generateDevelopmentBundle --no-daemon --stacktrace
      - name: Set Commit Hash
        id: set_commit_hash
        run: echo "COMMIT_HASH=$(git log --format='%H' -n 1)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Build ${{ github.run_number }}
          tag_name: ${{ github.run_number }}
          body: "What file to choose the IceCream Team recommends the paperclip reobf jar mojmap paperclip jar is fine but alot of plugins are not supported"
          token: ${{ secrets.TOKEN }}
          files: build/libs/*.jar
      - name: Github Releases To Discord
        continue-on-error: true
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "New IceCreamMC Release!"
          embed-url: "https://github.com/icecreammc/icecream/latest/releases"
          embed-description: "IceCreamMC has published a new update! Click [here](https://icecreammc.github.io/icecream/download) to download IceCreamMC!"
          embed-thumbnail-url: "https://avatars.githubusercontent.com/u/153784457?s=200&v=4"
      - name: Push To API
        continue-on-error: true
        if: "!contains(github.event.commits[0].message, '[release-skip]')"
        env:
          secret: ${{ secrets.API_PUSH_TOKEN }}
        tag: ${{ env.tag }}
      run: sh scripts/PushToAPI.sh